const fs = require('fs');
const code = fs.readFileSync('src/pages/IrradiationProtocol.jsx','utf8');
const lines = code.split('\n').length;

const sections = [
"9-ETHER IRRADIATION PROTOCOL — SUPREME RESONANCE + LUNAR BALANCE EDITION",
"Sacred Frequencies App | Cecilyn Williams",
"Saved: June 7, 2026 | Version: Supreme + Lunar | Source lines: " + lines,
"================================================================================",
"",
"PROTOCOL OVERVIEW",
"─────────────────",
"9 Etheric Dimensions · 3 Supreme Tiers · 4 Lunar Phases",
"Full spectrum: 7.83 Hz (Schumann) to 3,168 Hz (Christ Consciousness Grid)",
"Universal broadcast: all beings, all dimensions, all timelines simultaneously",
"",
"THE 9 ETHERS",
"─────────────",
"Ether 1  Physical   174 Hz  + 40 sub   + 2 Hz beat    | BASE     | Root",
"Ether 2  Cellular   333 Hz  + 111 sub  + 3 Hz beat    | BASE     | Sacral",
"Ether 3  Etheric    396 Hz  + 198 sub  + 4 Hz beat    + 417 supreme | ELEVATED | Solar Plexus",
"Ether 4  Emotional  528 Hz  + 264 sub  + 3.5 Hz beat  + 639 supreme | ELEVATED | Heart",
"Ether 5  Mental     741 Hz  + 370 sub  + 10 Hz beat   + 852 supreme | ELEVATED | Throat",
"Ether 6  Ancestral  417 Hz  + 208 sub  + 2 Hz beat    + 528 supreme | ELEVATED | Ancestral Heart",
"Ether 7  Spiritual  852 Hz  + 426 sub  + 7 Hz beat    + 963 supreme | ELEVATED | Third Eye",
"Ether 8  Quantum    963 Hz  + 481 sub  + 9 Hz beat    + 1111 supreme| SUPREME  | Crown",
"Ether 9  Akashic   1111 Hz  + 555 sub  + 9 Hz beat    + 1296 supreme| SUPREME  | Soul Star",
"",
"THREE SUPREME TIERS",
"────────────────────",
"Angelic Threshold    1,296 Hz (9x144 Fibonacci)  + 648 Hz sub",
"Solar Harmonic       2,160 Hz (432x5 Merkabah)   + 1,080 Hz sub",
"Christ Grid          3,168 Hz (528x6 — ceiling)  + 1,584 Hz sub",
"",
"LUNAR RESONANCE BALANCE SYSTEM",
"────────────────────────────────",
"New Moon  136.10 Hz  Earth/Om tone     sub 68.05   overlay 210.42  Yin void — deepest clearing",
"Waxing    210.42 Hz  Sidereal orbit    sub 105.21  overlay 229.22  Building new patterns",
"Full Moon 221.23 Hz  Lunar orbit peak  sub 110.61  overlay 432     Maximum amplification",
"Waning    229.22 Hz  Synodic month     sub 114.61  overlay 210.42  Permanent release",
"",
"LUNAR AFFIRMATIONS",
"───────────────────",
"New Moon : In the sacred void of the new moon, every irradiated space is cleansed",
"           to its deepest root. I receive the new template in perfect stillness.",
"Waxing   : As the moon grows, so does my health. Every cleared space fills now with",
"           radiant new life. I am building my highest, most luminous self.",
"Full Moon: Under the full moons perfect light, every frequency I carry is amplified",
"           a thousandfold. I am radiant, healed and whole in every dimension.",
"Waning   : As the moon releases its light, I release every last trace of what has",
"           been irradiated. It is gone. It cannot return. I am permanently free.",
"",
"SAFETY ARCHITECTURE",
"────────────────────",
"528 Hz love carrier       irradiates only what harms, heals what is healthy",
"7.83 Hz Schumann anchor   earth-safe grounding on every layer",
"Sub-octave (hz/2)         deep biological penetration on ethers 3-9",
"Supreme overlay Hz        lifts the field, never overwhelms",
"Violet flame 417 Hz       transmutes rather than suppresses",
"4 Hz tremolo pulse        Rife-pattern amplitude modulation",
"Golden ratio 1.618x       natures safe irradiation shimmer",
"Amazon forest undertone   nervous system calm throughout",
"3,168 Hz ceiling          highest confirmed safe biological resonance",
"",
"WHAT GETS IRRADIATED",
"─────────────────────",
"Physical    Parasites, worms, tissue masses, crystallised toxins, heavy metals",
"Cellular    Bacteria, fungi, viruses, Lyme, Candida, flukes — Rife MOR method",
"Etheric     Entity attachments, psychic cords, astral implants, dark imprints",
"Emotional   Trapped grief, rage, shame, fear, emotional parasites",
"Mental      Psychic implants, hypnotic programming, harmful thought-forms",
"Ancestral   7-generation epigenetic trauma, bloodline entities, karmic codes",
"Spiritual   Harmful soul contracts, karmic entanglements, dark initiations",
"Quantum     Timeline contamination, reality distortions, probability hijacking",
"Akashic     ALL remaining presences across ALL dimensions, timelines and beings",
"",
"RESTORATION SEQUENCE",
"─────────────────────",
"285 Hz    Cellular Rebuild      tissue regeneration after irradiation",
"528 Hz    DNA Template Seal     lock in the restored genetic blueprint",
"639 Hz    Heart Field Restore   rebuild love and connection",
"7.83 Hz   Earth Anchor          re-ground to planetary healing field",
"136.10 Hz New Moon Clearing     sacred Om deep yin clearing",
"221.23 Hz Full Moon Amplify     lunar peak amplification of healed field",
"1,296 Hz  Angelic Seal          seal with divine angelic light",
"432 Hz    Solar Protection      natures universal harmonic shield",
"",
"BEING TYPES AND FREQUENCY MODULATION",
"──────────────────────────────────────",
"Myself 1.00x | Family 1.00x | Child 1.10x | Elder 0.90x | Pregnant 1.05x",
"Dog 0.85x | Cat 0.95x | Horse 0.70x | Bird 1.15x | Reptile 0.80x",
"Plant/Tree 0.60x | All Beings 1.00x (universal broadcast)",
"",
"SCIENTIFIC REFERENCES",
"──────────────────────",
"Royal Rife (1934)          Mortal Oscillatory Rate and cellular irradiation",
"Fritz-Albert Popp (1984)   Biophotonic field coherence and healing",
"Hans Cousto                The Cosmic Octave — lunar frequency mathematics",
"Dr. Glen Rein              528 Hz increases DNA UV absorption by 11%",
"Rachel Yehuda et al.       Epigenetic trauma inheritance via FKBP5 methylation",
"HeartMath Institute        Heart coherence triggers 1,300+ gene expression changes",
"Bhattacharya (2016)        Pineal gland cavity resonance computational model",
"Rupert Sheldrake           Morphic resonance and non-local healing field theory",
"",
"================================================================================",
"COMPLETE SOURCE CODE (" + lines + " lines)",
"================================================================================",
"",
code
];

const doc = sections.join("\n");
require('fs').writeFileSync('exports/9_Ether_Protocol_Supreme_Lunar.txt', doc);
const size = require('fs').statSync('exports/9_Ether_Protocol_Supreme_Lunar.txt').size;
console.log('Created. Size:', size, 'bytes =', (size/1024).toFixed(1), 'KB');
